remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "elm-tooling-cli on GitHub":
    - "https://github.com/elm-tooling/elm-tooling-cli"
